import { Bookmarks } from "webextension-polyfill-ts";

const firefoxTree: Bookmarks.BookmarkTreeNode[] = [
	{
		id: "root________",
		title: "",
		index: 0,
		dateAdded: 1579020321826,
		type: "folder",
		dateGroupModified: 1579020323821,
		children: [
			{
				id: "menu________",
				title: "Bookmarks Menu",
				index: 0,
				dateAdded: 1579020321826,
				type: "folder",
				parentId: "root________",
				dateGroupModified: 1579020323821,
				children: [
					{
						id: "u8V2UsBINeWn",
						title: "Mozilla Firefox",
						index: 0,
						dateAdded: 1579020322410,
						type: "folder",
						parentId: "menu________",
						dateGroupModified: 1579020322410,
						children: [
							{
								id: "uL5X6NyM5O_t",
								title: "Help and Tutorials",
								index: 0,
								dateAdded: 1579020322410,
								type: "bookmark",
								url: "https://support.mozilla.org/en-US/products/firefox",
								parentId: "u8V2UsBINeWn",
							},
							{
								id: "Di7VyE0ae7tT",
								title: "Customize Firefox",
								index: 1,
								dateAdded: 1579020322410,
								type: "bookmark",
								url:
									"https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars?utm_source=firefox-browser&utm_medium=default-bookmarks&utm_campaign=customize",
								parentId: "u8V2UsBINeWn",
							},
							{
								id: "7sVghlk_d3BF",
								title: "Get Involved",
								index: 2,
								dateAdded: 1579020322410,
								type: "bookmark",
								url: "https://www.mozilla.org/en-US/contribute/",
								parentId: "u8V2UsBINeWn",
							},
							{
								id: "xAGy0rscJaT3",
								title: "About Us",
								index: 3,
								dateAdded: 1579020322410,
								type: "bookmark",
								url: "https://www.mozilla.org/en-US/about/",
								parentId: "u8V2UsBINeWn",
							},
						],
					},
					{
						id: "rFuesUMpsU8n",
						title: "Some folder",
						index: 1,
						dateAdded: 1579020323776,
						type: "folder",
						parentId: "menu________",
						dateGroupModified: 1579020323821,
						children: [
							{
								id: "CCvxcZMU3irX",
								title: "Doesn't exist",
								index: 0,
								dateAdded: 1579020323821,
								type: "bookmark",
								url: "https://427771893.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "xb5ZqCSWZp3Q",
								title: "Reddit: Programming",
								index: 1,
								dateAdded: 1579020323821,
								type: "bookmark",
								url: "https://www.reddit.com/r/programming",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "GA5bihksb6uv",
								title: "Hacker News",
								index: 2,
								dateAdded: 1579020323820,
								type: "bookmark",
								url: "https://news.ycombinator.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "KzX46SekOHDW",
								title: "Wikipedia bookmark with a very, very, very, very, very long title",
								index: 3,
								dateAdded: 1579020323820,
								type: "bookmark",
								url: "https://wikipedia.org/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "sdNbrzTyPa13",
								title: "Twitter",
								index: 4,
								dateAdded: 1579020323820,
								type: "bookmark",
								url: "https://twitter.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "zBDsRiNjZfyB",
								title: "Netflix",
								index: 5,
								dateAdded: 1579020323819,
								type: "bookmark",
								url: "https://netflix.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "RsDVNA1fgrry",
								title: "LinkedIn",
								index: 6,
								dateAdded: 1579020323819,
								type: "bookmark",
								url: "https://linkedin.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "DGlJcMLqXWHF",
								title: "Google",
								index: 7,
								dateAdded: 1579020323819,
								type: "bookmark",
								url: "https://google.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "deUwUyDRx5NT",
								title: "GitHub",
								index: 8,
								dateAdded: 1579020323818,
								type: "bookmark",
								url: "https://github.com/",
								parentId: "rFuesUMpsU8n",
							},
							{
								id: "Neekz9HDIopY",
								title: "Facebook",
								index: 9,
								dateAdded: 1579020323818,
								type: "bookmark",
								url: "https://facebook.com/",
								parentId: "rFuesUMpsU8n",
							},
						],
					},
					{
						id: "vBxMvi008Zxa",
						title: "Doesn't exist",
						index: 2,
						dateAdded: 1579020323776,
						type: "bookmark",
						url: "https://427771893.com/",
						parentId: "menu________",
					},
					{
						id: "nQIe2-OQfrTQ",
						title: "Reddit: Programming",
						index: 3,
						dateAdded: 1579020323770,
						type: "bookmark",
						url: "https://www.reddit.com/r/programming",
						parentId: "menu________",
					},
					{
						id: "W6ZBZLacJWLd",
						title: "Hacker News",
						index: 4,
						dateAdded: 1579020323770,
						type: "bookmark",
						url: "https://news.ycombinator.com/",
						parentId: "menu________",
					},
					{
						id: "fl92eFNVRY6n",
						title: "Wikipedia bookmark with a very, very, very, very, very long title",
						index: 5,
						dateAdded: 1579020323770,
						type: "bookmark",
						url: "https://wikipedia.org/",
						parentId: "menu________",
					},
					{
						id: "LLbITI04NiUX",
						title: "Twitter",
						index: 6,
						dateAdded: 1579020323769,
						type: "bookmark",
						url: "https://twitter.com/",
						parentId: "menu________",
					},
					{
						id: "9ra4ESyH5W78",
						title: "Netflix",
						index: 7,
						dateAdded: 1579020323769,
						type: "bookmark",
						url: "https://netflix.com/",
						parentId: "menu________",
					},
					{
						id: "hkzAJH8jj7FW",
						title: "LinkedIn",
						index: 8,
						dateAdded: 1579020323769,
						type: "bookmark",
						url: "https://linkedin.com/",
						parentId: "menu________",
					},
					{
						id: "glJbuFBp9M1w",
						title: "Google",
						index: 9,
						dateAdded: 1579020323769,
						type: "bookmark",
						url: "https://google.com/",
						parentId: "menu________",
					},
					{
						id: "vLMSkDFNHJMS",
						title: "GitHub",
						index: 10,
						dateAdded: 1579020323768,
						type: "bookmark",
						url: "https://github.com/",
						parentId: "menu________",
					},
					{
						id: "06lCLaFVBPLI",
						title: "Facebook",
						index: 11,
						dateAdded: 1579020323767,
						type: "bookmark",
						url: "https://facebook.com/",
						parentId: "menu________",
					},
				],
			},
			{
				id: "toolbar_____",
				title: "Bookmarks Toolbar",
				index: 1,
				dateAdded: 1579020321826,
				type: "folder",
				parentId: "root________",
				dateGroupModified: 1579020322439,
				children: [
					{
						id: "RYBD8XSq6mBF",
						title: "Getting Started",
						index: 0,
						dateAdded: 1579020322439,
						type: "bookmark",
						url: "https://www.mozilla.org/en-US/firefox/central/",
						parentId: "toolbar_____",
					},
				],
			},
			{
				id: "unfiled_____",
				title: "Other Bookmarks",
				index: 3,
				dateAdded: 1579020321826,
				type: "folder",
				parentId: "root________",
				dateGroupModified: 1579020322391,
				children: [],
			},
			{
				id: "mobile______",
				title: "Mobile Bookmarks",
				index: 4,
				dateAdded: 1579020321849,
				type: "folder",
				parentId: "root________",
				dateGroupModified: 1579020322391,
				children: [],
			},
		],
	},
];

export default firefoxTree;
