import { FlatTree } from "../../src/shared/types"

const firefoxFlatTree: FlatTree = {
  root________: {
    id: "root________",
    parentId: undefined,
    childrenIds: [
      "menu________",
      "toolbar_____",
      "unfiled_____",
      "mobile______",
    ],
    index: 0,
    type: "folder",
    title: "",
    url: undefined,
  },
  menu________: {
    id: "menu________",
    parentId: "root________",
    childrenIds: [
      "u8V2UsBINeWn",
      "rFuesUMpsU8n",
      "vBxMvi008Zxa",
      "nQIe2-OQfrTQ",
      "W6ZBZLacJWLd",
      "fl92eFNVRY6n",
      "LLbITI04NiUX",
      "9ra4ESyH5W78",
      "hkzAJH8jj7FW",
      "glJbuFBp9M1w",
      "vLMSkDFNHJMS",
      "06lCLaFVBPLI",
    ],
    index: 0,
    type: "folder",
    title: "Bookmarks Menu",
    url: undefined,
  },
  u8V2UsBINeWn: {
    id: "u8V2UsBINeWn",
    parentId: "menu________",
    childrenIds: [
      "uL5X6NyM5O_t",
      "Di7VyE0ae7tT",
      "7sVghlk_d3BF",
      "xAGy0rscJaT3",
    ],
    index: 0,
    type: "folder",
    title: "Mozilla Firefox",
    url: undefined,
  },
  uL5X6NyM5O_t: {
    id: "uL5X6NyM5O_t",
    parentId: "u8V2UsBINeWn",
    childrenIds: [],
    index: 0,
    type: "bookmark",
    title: "Help and Tutorials",
    url: "https://support.mozilla.org/en-US/products/firefox",
  },
  Di7VyE0ae7tT: {
    id: "Di7VyE0ae7tT",
    parentId: "u8V2UsBINeWn",
    childrenIds: [],
    index: 1,
    type: "bookmark",
    title: "Customize Firefox",
    url: "https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars?utm_source=firefox-browser&utm_medium=default-bookmarks&utm_campaign=customize",
  },
  "7sVghlk_d3BF": {
    id: "7sVghlk_d3BF",
    parentId: "u8V2UsBINeWn",
    childrenIds: [],
    index: 2,
    type: "bookmark",
    title: "Get Involved",
    url: "https://www.mozilla.org/en-US/contribute/",
  },
  xAGy0rscJaT3: {
    id: "xAGy0rscJaT3",
    parentId: "u8V2UsBINeWn",
    childrenIds: [],
    index: 3,
    type: "bookmark",
    title: "About Us",
    url: "https://www.mozilla.org/en-US/about/",
  },
  rFuesUMpsU8n: {
    id: "rFuesUMpsU8n",
    parentId: "menu________",
    childrenIds: [
      "CCvxcZMU3irX",
      "xb5ZqCSWZp3Q",
      "GA5bihksb6uv",
      "KzX46SekOHDW",
      "sdNbrzTyPa13",
      "zBDsRiNjZfyB",
      "RsDVNA1fgrry",
      "DGlJcMLqXWHF",
      "deUwUyDRx5NT",
      "Neekz9HDIopY",
    ],
    index: 1,
    type: "folder",
    title: "Some folder",
    url: undefined,
  },
  CCvxcZMU3irX: {
    id: "CCvxcZMU3irX",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 0,
    type: "bookmark",
    title: "Doesn't exist",
    url: "https://427771893.com/",
  },
  xb5ZqCSWZp3Q: {
    id: "xb5ZqCSWZp3Q",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 1,
    type: "bookmark",
    title: "Reddit: Programming",
    url: "https://www.reddit.com/r/programming",
  },
  GA5bihksb6uv: {
    id: "GA5bihksb6uv",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 2,
    type: "bookmark",
    title: "Hacker News",
    url: "https://news.ycombinator.com/",
  },
  KzX46SekOHDW: {
    id: "KzX46SekOHDW",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 3,
    type: "bookmark",
    title: "Wikipedia bookmark with a very, very, very, very, very long title",
    url: "https://wikipedia.org/",
  },
  sdNbrzTyPa13: {
    id: "sdNbrzTyPa13",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 4,
    type: "bookmark",
    title: "Twitter",
    url: "https://twitter.com/",
  },
  zBDsRiNjZfyB: {
    id: "zBDsRiNjZfyB",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 5,
    type: "bookmark",
    title: "Netflix",
    url: "https://netflix.com/",
  },
  RsDVNA1fgrry: {
    id: "RsDVNA1fgrry",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 6,
    type: "bookmark",
    title: "LinkedIn",
    url: "https://linkedin.com/",
  },
  DGlJcMLqXWHF: {
    id: "DGlJcMLqXWHF",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 7,
    type: "bookmark",
    title: "Google",
    url: "https://google.com/",
  },
  deUwUyDRx5NT: {
    id: "deUwUyDRx5NT",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 8,
    type: "bookmark",
    title: "GitHub",
    url: "https://github.com/",
  },
  Neekz9HDIopY: {
    id: "Neekz9HDIopY",
    parentId: "rFuesUMpsU8n",
    childrenIds: [],
    index: 9,
    type: "bookmark",
    title: "Facebook",
    url: "https://facebook.com/",
  },
  vBxMvi008Zxa: {
    id: "vBxMvi008Zxa",
    parentId: "menu________",
    childrenIds: [],
    index: 2,
    type: "bookmark",
    title: "Doesn't exist",
    url: "https://427771893.com/",
  },
  "nQIe2-OQfrTQ": {
    id: "nQIe2-OQfrTQ",
    parentId: "menu________",
    childrenIds: [],
    index: 3,
    type: "bookmark",
    title: "Reddit: Programming",
    url: "https://www.reddit.com/r/programming",
  },
  W6ZBZLacJWLd: {
    id: "W6ZBZLacJWLd",
    parentId: "menu________",
    childrenIds: [],
    index: 4,
    type: "bookmark",
    title: "Hacker News",
    url: "https://news.ycombinator.com/",
  },
  fl92eFNVRY6n: {
    id: "fl92eFNVRY6n",
    parentId: "menu________",
    childrenIds: [],
    index: 5,
    type: "bookmark",
    title: "Wikipedia bookmark with a very, very, very, very, very long title",
    url: "https://wikipedia.org/",
  },
  LLbITI04NiUX: {
    id: "LLbITI04NiUX",
    parentId: "menu________",
    childrenIds: [],
    index: 6,
    type: "bookmark",
    title: "Twitter",
    url: "https://twitter.com/",
  },
  "9ra4ESyH5W78": {
    id: "9ra4ESyH5W78",
    parentId: "menu________",
    childrenIds: [],
    index: 7,
    type: "bookmark",
    title: "Netflix",
    url: "https://netflix.com/",
  },
  hkzAJH8jj7FW: {
    id: "hkzAJH8jj7FW",
    parentId: "menu________",
    childrenIds: [],
    index: 8,
    type: "bookmark",
    title: "LinkedIn",
    url: "https://linkedin.com/",
  },
  glJbuFBp9M1w: {
    id: "glJbuFBp9M1w",
    parentId: "menu________",
    childrenIds: [],
    index: 9,
    type: "bookmark",
    title: "Google",
    url: "https://google.com/",
  },
  vLMSkDFNHJMS: {
    id: "vLMSkDFNHJMS",
    parentId: "menu________",
    childrenIds: [],
    index: 10,
    type: "bookmark",
    title: "GitHub",
    url: "https://github.com/",
  },
  "06lCLaFVBPLI": {
    id: "06lCLaFVBPLI",
    parentId: "menu________",
    childrenIds: [],
    index: 11,
    type: "bookmark",
    title: "Facebook",
    url: "https://facebook.com/",
  },
  toolbar_____: {
    id: "toolbar_____",
    parentId: "root________",
    childrenIds: ["RYBD8XSq6mBF"],
    index: 1,
    type: "folder",
    title: "Bookmarks Toolbar",
    url: undefined,
  },
  RYBD8XSq6mBF: {
    id: "RYBD8XSq6mBF",
    parentId: "toolbar_____",
    childrenIds: [],
    index: 0,
    type: "bookmark",
    title: "Getting Started",
    url: "https://www.mozilla.org/en-US/firefox/central/",
  },
  unfiled_____: {
    id: "unfiled_____",
    parentId: "root________",
    childrenIds: [],
    index: 3,
    type: "folder",
    title: "Other Bookmarks",
    url: undefined,
  },
  mobile______: {
    id: "mobile______",
    parentId: "root________",
    childrenIds: [],
    index: 4,
    type: "folder",
    title: "Mobile Bookmarks",
    url: undefined,
  },
}

export default firefoxFlatTree
